/**
 * OpenNano-CRM — PDF service
 *
 * Renders a view's layout + record data to HTML, then to PDF.
 * Primary: puppeteer (headless Chromium). Fallback: pdf-lib for environments
 * without a browser (e.g. minimal Docker images).
 */

export interface PdfOptions {
  layout: any;
  record: Record<string, unknown>;
  tableLabel: string;
}

function layoutToHtml(opts: PdfOptions): string {
  const { layout, record, tableLabel } = opts;
  const sections = (layout?.sections ?? []) as any[];
  const rows = sections
    .map(
      (s) => `
    <section style="margin-bottom:16px">
      ${s.title ? `<h2 style="font-size:14px;margin:0 0 8px">${s.title}</h2>` : ""}
      <div style="display:grid;grid-template-columns:repeat(${s.cols ?? 2},1fr);gap:12px">
        ${(s.fields ?? [])
          .filter((f: any) => !f.hidden)
          .map(
            (f: any) => `
          <div style="border:1px solid #e5e7eb;padding:8px;border-radius:6px">
            <div style="font-size:11px;color:#6b7280">${f.name}</div>
            <div style="font-size:13px">${String(record[f.name] ?? "—")}</div>
          </div>`,
          )
          .join("")}
      </div>
    </section>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"><title>${tableLabel} #${record.id}</title></head>
  <body style="font-family:system-ui;padding:24px">
    <h1 style="font-size:18px">${tableLabel} — Record #${record.id}</h1>
    ${rows || `<p>No layout — showing raw fields</p><pre>${JSON.stringify(record, null, 2)}</pre>`}
    <p style="font-size:11px;color:#9ca3af;margin-top:24px">Generated by OpenNano-CRM</p>
  </body></html>`;
}

export async function renderPdf(opts: PdfOptions): Promise<Uint8Array> {
  const html = layoutToHtml(opts);

  // Try puppeteer if available (optional dep)
  try {
    // @ts-ignore - optional peer dep
    const puppeteer: any = await import("puppeteer").catch(() => null);
    if (puppeteer?.launch) {
      const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdf = await page.pdf({ format: "A4", printBackground: true });
      await browser.close();
      return pdf;
    }
  } catch {
    // fall through to pdf-lib
  }

  // Fallback: very small pdf-lib stub (text-only)
  const { PDFDocument, StandardFonts } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  page.drawText(`${opts.tableLabel} #${opts.record.id}`, { x: 50, y: 800, size: 14, font });
  page.drawText(JSON.stringify(opts.record, null, 2).slice(0, 3000), { x: 50, y: 750, size: 8, font });
  return doc.save();
}
