/**
 * OpenNano-CRM — PDF service
 *
 * Renders a view's layout + record data to HTML, then to PDF.
 * Primary: puppeteer (headless Chromium). Fallback: pdf-lib for environments
 * without a browser (e.g. minimal Docker images).
 */

export interface PdfOptions {
  layout: any;
  record: Record<string, unknown>;
  tableLabel: string;
}

export interface ReportPdfOptions {
  report: { label: string; layout: any };
  projectLabel: string;
  organizationLabel: string;
}

function layoutToHtml(opts: PdfOptions): string {
  const { layout, record, tableLabel } = opts;
  const sections = (layout?.sections ?? []) as any[];
  const rows = sections
    .map(
      (s) => `
    <section style="margin-bottom:16px">
      ${s.title ? `<h2 style="font-size:14px;margin:0 0 8px">${s.title}</h2>` : ""}
      <div style="display:grid;grid-template-columns:repeat(${s.cols ?? 2},1fr);gap:12px">
        ${(s.fields ?? [])
          .filter((f: any) => !f.hidden)
          .map(
            (f: any) => `
          <div style="border:1px solid #e5e7eb;padding:8px;border-radius:6px">
            <div style="font-size:11px;color:#6b7280">${f.label ?? f.name}</div>
            <div style="font-size:13px">${String(record[f.name] ?? "—")}</div>
          </div>`,
          )
          .join("")}
      </div>
    </section>`,
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8"><title>${tableLabel} #${record.id}</title></head>
  <body style="font-family:system-ui;padding:24px">
    <h1 style="font-size:18px">${tableLabel} — Record #${record.id}</h1>
    ${rows || `<p>No layout — showing raw fields</p><pre>${JSON.stringify(record, null, 2)}</pre>`}
    <p style="font-size:11px;color:#9ca3af;margin-top:24px">Generated by OpenNano-CRM</p>
  </body></html>`;
}

export async function renderPdf(opts: PdfOptions): Promise<Uint8Array> {
  const html = layoutToHtml(opts);

  // Try puppeteer if available (optional dep)
  try {
    // @ts-ignore - optional peer dep
    const puppeteer: any = await import("puppeteer").catch(() => null);
    if (puppeteer?.launch) {
      const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdf = await page.pdf({ format: "A4", printBackground: true });
      await browser.close();
      return pdf;
    }
  } catch {
    // fall through to pdf-lib
  }

  // Fallback: preserve the selected layout when Chromium is unavailable.
  const { PDFDocument, StandardFonts } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  let page = doc.addPage([595, 842]);
  let y = 790;
  const draw = (text: string, size = 10) => {
    if (y < 55) {
      page = doc.addPage([595, 842]);
      y = 790;
    }
    page.drawText(text.slice(0, 105), { x: 50, y, size, font });
    y -= size + 8;
  };
  draw(`${opts.tableLabel} #${opts.record.id}`, 16);
  for (const section of (opts.layout?.sections ?? []) as any[]) {
    if (section.title) draw(section.title, 12);
    for (const field of (section.fields ?? []).filter((item: any) => !item.hidden)) {
      draw(`${field.label ?? field.name}: ${String(opts.record[field.name] ?? "—")}`, 10);
    }
  }
  if (!opts.layout?.sections?.length) draw(JSON.stringify(opts.record, null, 2), 8);
  draw("Generated by OpenNano-CRM", 8);
  return doc.save();
}

export async function renderReportPdf(opts: ReportPdfOptions): Promise<Uint8Array> {
  const layout = opts.report.layout ?? {};
  const blocks = (layout.blocks ?? []) as any[];
  const htmlBlocks = blocks.map((block) => {
    if (block.kind === "spacer") return `<div style="height:24px"></div>`;
    if (block.kind === "heading") return `<h2 style="font-size:16px;margin:18px 0 8px">${block.text ?? block.label}</h2>`;
    return `<div style="border-bottom:1px solid #e5e7eb;padding:10px 0"><div style="font-size:11px;color:#6b7280">${block.label}</div><div style="font-size:14px;color:#111827">—</div></div>`;
  }).join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${opts.report.label}</title></head><body style="font-family:system-ui;padding:32px"><div style="font-size:11px;color:#6b7280">${opts.organizationLabel} / ${opts.projectLabel}</div><h1 style="font-size:24px;margin:8px 0">${layout.title ?? opts.report.label}</h1><p style="color:#6b7280">${layout.subtitle ?? ""}</p>${htmlBlocks}<footer style="font-size:10px;color:#9ca3af;margin-top:32px">Generated by OpenNano-CRM</footer></body></html>`;
  try {
    // @ts-ignore - optional peer dep
    const puppeteer: any = await import("puppeteer").catch(() => null);
    if (puppeteer?.launch) {
      const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdf = await page.pdf({ format: "A4", printBackground: true });
      await browser.close();
      return pdf;
    }
  } catch {}
  const { PDFDocument, StandardFonts } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  let page = doc.addPage([595, 842]);
  let y = 790;
  const draw = (text: string, size = 10) => {
    if (y < 55) { page = doc.addPage([595, 842]); y = 790; }
    page.drawText(text.slice(0, 105), { x: 50, y, size, font });
    y -= size + 9;
  };
  draw(`${opts.organizationLabel} / ${opts.projectLabel}`, 9);
  draw(layout.title ?? opts.report.label, 18);
  if (layout.subtitle) draw(layout.subtitle, 10);
  for (const block of blocks) {
    if (block.kind === "spacer") { y -= 16; continue; }
    draw(block.kind === "heading" ? (block.text ?? block.label) : `${block.label}: —`, block.kind === "heading" ? 13 : 10);
  }
  draw("Generated by OpenNano-CRM", 8);
  return doc.save();
}
